name: Downloading and Using the Artifact

on:
  push:
    branches:
      - main

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact File
        run: echo "This is a test file created in GitHub Actions" > artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt

  download-and-use-artifact:
    runs-on: ubuntu-latest
    needs: create-and-upload-artifact
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./artifacts

      - name: Print Artifact File Content
        run: cat artifacts/artifact.txt
`