name: Working with Variables

on:
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Print GitHub Context Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Head Ref: ${{ github.head_ref }}" # populated for workflows triggered by pull request events
          echo "Base Ref: ${{ github.base_ref }}" # populated for workflows triggered by pull request events
          echo "Job: ${{ github.job }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
          echo "Repository Owner: ${{ github.event.repository.owner.login }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Repository Full Name: ${{ github.event.repository.full_name }}"
          echo "Repository URL: ${{ github.event.repository.html_url }}"
          echo "Repository Description: ${{ github.event.repository.description }}"
      
      - name: Print Environment Variables
        env:
          MY_ENV_VAR: "This is an environment variable"
        run: |
          echo "Environment Variable: $MY_ENV_VAR"
      
      - name: Print Repository Variables
        run: |
          echo "Repository Variable in Test Environment: ${{ vars.MY_VAR }}"
          echo "Repository Variable: ${{ vars.REPO_VAR }}"
      
      - name: Print Secrets
        run: |
          echo "Repository Secret in Test Environment: ${{ secrets.MY_SECRET }}"
          echo "Repository Secret: ${{ secrets.REPO_SECRET }}"