name: Working with Variables

on:
  push:
    branches:
      - main

  jobs:
    display-variables:
      runs-on: ubuntu-latest
      steps:
        - name: Print GitHub Context Variables
          run: |
            echo "Repository: ${{ github.repository }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Actor: ${{ github.actor }}"
            echo "Event Name: ${{ github.event_name }}"
            echo "Ref: ${{ github.ref }}"
            echo "SHA: ${{ github.sha }}"
            echo "Head Ref: ${{ github.head_ref }}"
            echo "Base Ref: ${{ github.base_ref }}"
        
        - name: Print Environment Variables
          env:
            MY_ENV_VAR: "This is an environment variable"
          run: |
            echo "Environment Variable: $MY_ENV_VAR"
        
        - name: Print Repository Variables
          run: |
            echo "Repository Variable: ${{ vars.MY_VAR }}"
        
        - name: Print Secrets
          run: |
            echo "Secret: ${{ secrets.MY_SECRET }}"