name: Multi-OS and Multi-Node.js Testing

on:
  push:
    branches:
    - main

jobs:
  multi-os-node-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16, 18]
				
    steps:
      - name: setup node
        uses: actions/setup-node
        with:
          node-version: ${{ matrix.node }}
					
