name: Multi-OS and Multi-Node.js Testing

on:
  workflow_dispatch:

jobs:
  multi-os-node-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16, 18]
        exclude:
          - os: macos-latest #node version 14 not available on macos(arm64)
            node: 14

    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}