name: Conditional Job Execution

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo "hi"

  conditional-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
    - name: Conditional job 
      if: ${{ needs.first-job.result == 'success' }}
      run: echo "Condition passed"