name: Store and Upload a File as an Artifact

on:
  push:
    branches:
      - main

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact File
        run: echo "This is a test file created in GitHub Actions" > artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt
